---
- hosts: localhost
  gather_facts: no
  tasks:
    - hashivault_auth_list:
      register: 'vault_auth_list'
    - block:
      - hashivault_auth_enable:
          name: "userpass"
        failed_when: False
        register: 'vault_auth_enable'
      - assert: { that: "{{vault_auth_enable.changed}} == False" }
      - assert: { that: "{{vault_auth_enable.failed}} == False" }
      - assert: { that: "'{{vault_auth_enable.msg}}' == 'Exception: path is already in use'" }
      - assert: { that: "{{vault_auth_enable.rc}} == 1" }
      when: "'userpass/' in vault_auth_list.backends"
    - block:
      - hashivault_auth_enable:
          name: "userpass"
        register: 'vault_auth_enable'
      - assert: { that: "{{vault_auth_enable.changed}} == True" }
      - assert: { that: "{{vault_auth_enable.rc}} == 0" }
      when: "'userpass/' not in vault_auth_list.backends"
